    <div id="modalConfirmDeleteOpinion" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Delete Opinion</h3>
        </div>
        <div class="modal-body" style="text-align: center;">
            Are you sure you want to delete this opinion?
        </div>
        <div class="modal-footer">
            <a href="#" class="delete-confirmed btn btn-mini">Yes</a>
            <a href="#" class="delete-cancelled btn btn-mini">No</a>
        </div>
    </div>

    <div id="modalConfirmDeletePhoto" class="modal hide fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h3>Delete Photo</h3>
        </div>
        <div class="modal-body" style="text-align: center;">
            Are you sure you want to delete your photo?
        </div>
        <div class="modal-footer">
            <a href="#" class="delete-confirmed btn btn-mini">Yes</a>
            <a href="#" class="delete-cancelled btn btn-mini">No</a>
        </div>
    </div>

